$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: green
endpoint_name: my-endpoint
# model:
#   local_path: ../model/sklearn_regression_model.pkl
code_configuration:
  code: 
    local_path: ../src/
  scoring_script: managed_online_endpoint.py
environment: 
  conda_file: ../../controller/environments/managed-online-endpoint.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210727.v1
instance_type: Standard_F2s_v2
instance_count: 1
