variables:

# Workspace settings
  ml_workspace_connection: Azure-ARM-Dev
  ml_workspace_name: main
  ml_workspace_rg: azureml-examples-rg

# Managed Endpoints
  endpoint_name: testEndpoint1  #no spaces or _ allowed; only lowercase, caps, and -
  model: ../model/sklearn_regression_model.pkl  #does not work with local paths
  deployment_name: blue
  deployment_file: blue-deployment.yml
  traffic_allocation: blue=90 green=10 
